<?php
# make_vocabulary_list.php
# 
# This generates the vocabulary.list file, used by load_vocabulary.
#
# This also checks for duplicates as the vocabulary.list is being
# generated.

$file_list = array (
  'dairy.list',
  'dessert-sweet.list',
  'fruit-vegetable.list',
  'grain-bread-pasta.list',
  'protein.list');

# This is the file we're creating. We're going to open it and truncate
# it, so it's a new file every time this runs.
$vocab_list_file = fopen("vocabulary.list",'w');

fwrite($vocab_list_file, 
  "# NOTE: THIS FILE IS AUTO-GENERATED BY make_vocabulary_list.php.\n#\n" . 
  "# This is the vocabulary list. This list is a colon-separted list. This\n" .
  "# list contains the food vocabulary. The very first term is the most\n" .
  "# specific tag. Every tag after the first (separated by a colon) is the\n" .
  "# food group it belongs to.\n");

$seen = array(); # Checks for duplicates!

foreach ($file_list as $filename) {
  $food_group = preg_replace("/.list$/", "", $filename);
  # To detect an obscure case such as "protein:protein"
  $seen[$food_group] = "$food_group";
  $lines = file($filename, FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES);
  $line_count = 0;
  foreach ($lines as $line_num => $line) {
    if (substr($line, 0, 1) != "#") {
      $line = chop($line);
      # A $line can be either:
      # egg,eggs (a singular and a plural form, separated by a comma, no space)
      # OR
      # lettuce (just a singular form)
      $terms = explode(',',$line);
      foreach ($terms as $term) {
        if (preg_match('/\s/', $term)) {
          print "$term has a space in it (in $filename). FIX THIS BEFORE CONTINUING!\n";
        }
        if (array_key_exists($term, $seen)) {
          print "I've seen $term before in " . $seen[$term] . ". It's here again in $food_group. FIX THIS BEFORE CONTINUING!\n";
          continue;
        }
        $seen[$term] = "$food_group";
      }
      fwrite($vocab_list_file, "$line:$food_group\n");
      $line_count++;
    }
  }
  print "Wrote $line_count lines to vocabulary.list from $filename.\n";
}

fclose($vocab_list_file);
?>
